export const STATEMENT_STATUS = {
  GENERATED: "GENERATED",
  PENDING_SETTLEMENT: "PENDING_SETTLEMENT",
  MARKED_SETTLED_BY_LP: "MARKED_SETTLED_BY_LP",
  ACCEPTED_BY_STORE: "ACCEPTED_BY_STORE",
  DISPUTED: "DISPUTED",
  CLOSED: "CLOSED",
} as const;

export type StatementStatus =
  (typeof STATEMENT_STATUS)[keyof typeof STATEMENT_STATUS];
