export const MISMATCH_REASON = {
  PRODUCT_MISSING_ON_LP_SIDE: "PRODUCT_MISSING_ON_LP_SIDE",
  PRODUCT_MISSING_ON_STORE_SIDE: "PRODUCT_MISSING_ON_STORE_SIDE",
  BARCODE_NOT_RECOGNIZED: "BARCODE_NOT_RECOGNIZED",
  SKU_FALLBACK_USED: "SKU_FALLBACK_USED",
  UNIT_QUANTITY_MISMATCH: "UNIT_QUANTITY_MISMATCH",
  PRICE_DATA_MISSING: "PRICE_DATA_MISSING",
  PRODUCT_NOT_IN_PORTFOLIO: "PRODUCT_NOT_IN_PORTFOLIO",
  INVALID_ROW_DATE: "INVALID_ROW_DATE",
} as const;

export type MismatchReason =
  (typeof MISMATCH_REASON)[keyof typeof MISMATCH_REASON];
